### ISSUE TITLE
Error while creating the container

### ISSUE THREAD

**Issue by bachrc** [nhurel/nylas-sync-engine#12]
Your docker image would save me, but it seems that I can't run it.

When I try to run it from the Docker hub : 

```
pacha@obsidienne:~/nylas-sync$ sudo docker run --name nylassync nhurel/nylas-sync-engine
Traceback (most recent call last):
  File "bin/create-db", line 10, in <module>
    from inbox.ignition import init_db, build_uri, EngineManager, verify_db
  File "/opt/sync-engine/inbox/ignition.py", line 142, in <module>
    config.get_required('DATABASE_USERS'))
  File "/opt/sync-engine/inbox/ignition.py", line 132, in __init__
    port=port)
  File "/opt/sync-engine/inbox/ignition.py", line 37, in build_uri
    password=urlquote(password),
  File "/usr/lib/python2.7/urllib.py", line 1272, in quote_plus
    if ' ' in s:
TypeError: argument of type 'NoneType' is not iterable
 * Restarting with stat
Traceback (most recent call last):
  File "/opt/sync-engine/bin/inbox-start", line 29, in <module>
    from inbox.mailsync.service import SyncService
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/sync-engine/inbox/mailsync/service.py", line 12, in <module>
    from inbox.contacts.remote_sync import ContactSync
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/sync-engine/inbox/contacts/remote_sync.py", line 8, in <module>
    from inbox.models import Contact, Account
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/sync-engine/inbox/models/__init__.py", line 31, in <module>
    from inbox.models.backends import module_registry as backend_module_registry  # noqa
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/sync-engine/inbox/models/backends/__init__.py", line 8, in <module>
    module_registry = register_backends(__name__, __path__)
  File "/opt/sync-engine/inbox/util/misc.py", line 182, in register_backends
    modules = load_modules(base_name, base_path)
  File "/opt/sync-engine/inbox/util/misc.py", line 168, in load_modules
    full_module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/opt/sync-engine/inbox/models/backends/gmail.py", line 12, in <module>
    from inbox.models.session import session_scope
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/sync-engine/inbox/models/session.py", line 11, in <module>
    from inbox.ignition import engine_manager
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/sync-engine/inbox/ignition.py", line 142, in <module>
    config.get_required('DATABASE_USERS'))
  File "/opt/sync-engine/inbox/ignition.py", line 132, in __init__
    port=port)
  File "/opt/sync-engine/inbox/ignition.py", line 37, in build_uri
    password=urlquote(password),
  File "/usr/lib/python2.7/urllib.py", line 1272, in quote_plus
    if ' ' in s:
TypeError: argument of type 'NoneType' is not iterable
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/sync-engine/bin/inbox-api", line 56, in <lambda>
    run_with_reloader(lambda: start(port, start_syncback))
  File "/opt/sync-engine/bin/inbox-api", line 63, in start
    from inbox.api.srv import app
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/sync-engine/inbox/api/srv.py", line 6, in <module>
    from inbox.api.kellogs import APIEncoder
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/sync-engine/inbox/api/kellogs.py", line 7, in <module>
    from inbox.models import (Message, Contact, Calendar, Event, When,
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/sync-engine/inbox/models/__init__.py", line 31, in <module>
    from inbox.models.backends import module_registry as backend_module_registry  # noqa
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/sync-engine/inbox/models/backends/__init__.py", line 8, in <module>
    module_registry = register_backends(__name__, __path__)
  File "/opt/sync-engine/inbox/util/misc.py", line 182, in register_backends
    modules = load_modules(base_name, base_path)
  File "/opt/sync-engine/inbox/util/misc.py", line 168, in load_modules
    full_module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/opt/sync-engine/inbox/models/backends/gmail.py", line 12, in <module>
    from inbox.models.session import session_scope
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/sync-engine/inbox/models/session.py", line 11, in <module>
    from inbox.ignition import engine_manager
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/sync-engine/inbox/ignition.py", line 142, in <module>
    config.get_required('DATABASE_USERS'))
  File "/opt/sync-engine/inbox/ignition.py", line 132, in __init__
    port=port)
  File "/opt/sync-engine/inbox/ignition.py", line 37, in build_uri
    password=urlquote(password),
  File "/usr/lib/python2.7/urllib.py", line 1272, in quote_plus
    if ' ' in s:
TypeError: argument of type 'NoneType' is not iterable

s6-svscan: warning: unable to exec finish script .s6-svscan/finish: No such file or directory
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan: fatal: unable to exec .s6-svscan/crash: No such file or directory
```

So I tried to clone the github repo and then build it, but I have the same error... You have any idea ? Thanks !

**Comment by nhurel** [comment]
As mentionned in the README, this container needs to be linked to a mysql and redis container. The easiest way to do this is by using docker-compose and a docker-compose.yml file as the one given in example in the README.

**Comment by bachrc** [comment]
... Yeah, didn't know about this docker-compose thing.
So, I learned how it worked, and launched my `sudo docker-compose up` , but it seems that he has a problem with "Unknown databse 'inbox_2'".

```
sync-engine_1  | {"level": "warning", "timestamp": "2016-10-20T16:29:58.643548Z", "module": "contextlib:35", "greenlet_id": 87620496, "original_exception": "<class 'sqlalchemy.exc.OperationalError'>", "event": "Encountered OperationalError on rollback"}
sync-engine_1  | {"error_message": "(_mysql_exceptions.OperationalError) (1049, \"Unknown database 'inbox_2'\")", "account_id": null, "timestamp": "2016-10-20T16:29:58.647578Z", "provider": null, "module": "inbox.util.concurrency:106", "occurrences": 1, "greenlet_id": 87620496, "event": "Uncaught error", "level": "error", "error_tb": "Traceback (most recent call last):\n\t  File \"/opt/sync-engine/inbox/util/concurrency.py\", line 56, in wrapped\n    return func(*args, **kwargs)\n\t  File \"/opt/sync-engine/inbox/scheduling/queue.py\", line 148, in _run_impl\n    self.enqueue_new_accounts()\n\t  File \"/opt/sync-engine/inbox/scheduling/queue.py\", line 163, in enqueue_new_accounts\n    new_accounts = self.runnable_accounts() - self.queue_client.all()\n\t  File \"/opt/sync-engine/inbox/scheduling/queue.py\", line 184, in runnable_accounts\n    Account.sync_should_run))\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py\", line 2761, in __iter__\n    return self._execute_and_instances(context)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py\", line 2774, in _execute_and_instances\n    close_with_result=True)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py\", line 2765, in _connection_from_session\n    **kw)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py\", line 893, in connection\n    execution_options=execution_options)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py\", line 898, in _connection_for_bind\n    engine, execution_options)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py\", line 334, in _connection_for_bind\n    conn = bind.contextual_connect()\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 2039, in contextual_connect\n    self._wrap_pool_connect(self.pool.connect, None),\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 2078, in _wrap_pool_connect\n    e, dialect, self)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 1405, in _handle_dbapi_exception_noconnection\n    exc_info\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py\", line 202, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py\", line 2074, in _wrap_pool_connect\n    return fn()\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 376, in connect\n    return _ConnectionFairy._checkout(self)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 713, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 480, in checkout\n    rec = pool._do_get()\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 1060, in _do_get\n    self._dec_overflow()\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py\", line 60, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 1057, in _do_get\n    return self._create_connection()\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 323, in _create_connection\n    return _ConnectionRecord(self)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 449, in __init__\n    self.connection = self.__connect()\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py\", line 607, in __connect\n    connection = self.__pool._invoke_creator(self)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py\", line 97, in connect\n    return dialect.connect(*cargs, **cparams)\n\t  File \"/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py\", line 385, in connect\n    return self.dbapi.connect(*cargs, **cparams)\n\t  File \"/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py\", line 81, in Connect\n    return Connection(*args, **kwargs)\n\t  File \"/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py\", line 204, in __init__\n    super(Connection, self).__init__(*args, **kwargs2)\n\tOperationalError: (_mysql_exceptions.OperationalError) (1049, \"Unknown database 'inbox_2'\")\n", "error": "OperationalError"}
```

This error keeps displaying. So I tried to launch docker-compose in a detached mode, waited a little, and then launched the script you mentionned : 

```
docker exec -it nylas-sync-engine bash
bin/create-db
exit
```

But this error is showing..

```
pacha@obsidienne:~/nylas-sync/nylas-sync-engine$ sudo docker exec -it nylassyncengine_sync-engine_1 bash
root@sync-engine:/opt/sync-engine# bin/create-db
Setting up database: inbox
/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:450: Warning: Can't create database 'inbox'; database exists
  cursor.execute(statement, parameters)
Already revisioned by alembic version: 3df39f4fbdec
Verifying database.
Finished setting up database.

Setting up database: inbox_1
/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:450: Warning: Can't create database 'inbox_1'; database exists
  cursor.execute(statement, parameters)
Already revisioned by alembic version: 3df39f4fbdec
Verifying database.
Traceback (most recent call last):
  File "bin/create-db", line 85, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 659, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "bin/create-db", line 79, in main
    verify_db(engine, schema_name, int(key))
  File "/opt/sync-engine/inbox/ignition.py", line 188, in verify_db
    table, increment, key)
AssertionError: table: account, increment: 1, key: 1
```

And yeah, I tried to connect to the API via a web-browser. It's displaying this : 

```
{
  "message": "(_mysql_exceptions.OperationalError) (1049, \"Unknown database 'inbox_2'\")",
  "type": "api_error"
}
```

Just as the first's error is displaying. An error with the inbox_2 . That a weird error..

**Comment by nhurel** [comment]
Can you try the following : 
- Make sure to stop and rm the all 3 containers `docker-compose stop && docker-compose rm -f`
- Make sure to delete all the volumes : `docker volume list` to see the volumes and `docker volume rm <volumename>` to delete them
- Start only the mysql container with `docker-compose up -d mysql`
- Start the other containers with `docker-compose up -d`

I think the issue you encountered is due to the sync-engine container trying to create its database before the mysql container is ready. Using this 2-steps startup should work. 
Once the sync-engine has created its databases fine, other restart can be done with a single `docker-compose up -d`.

**Comment by bachrc** [comment]
Yeah, it seems to be working. Thanks for your work !
