### ISSUE TITLE
Can't create accounts anymore

### ISSUE THREAD

**Issue by miguelrs** [nhurel/nylas-sync-engine#17]
I gave this repo a try some weeks ago and got it working correctly, and then I removed the containers and everything from Docker...

Now I wanted to make it work again, and I can't create accounts anymore... I first removed everything with this instructions you posted in other issue:

```
docker-compose stop && docker-compose rm -f
docker volume rm nylas_part nylas_redis nylas_mysql
```

And then up again with:

```
docker-compose up -d mysql
docker-compose up -d
```

I get some warnings in the logs, but it seems to get the containers running and the DB initialised... However, when I try to create an account with `root@sync-engine:/opt/sync-engine# sudo -uinbox bin/inbox-auth my-email@gmail.com`, I get this error:

```
Traceback (most recent call last):
  File "bin/inbox-auth", line 11, in <module>
    from inbox.config import config
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named config
```

Am I missing some step? iirc it wasn't any difficult last time I got it working 🤔 

---

Note 1: I tried running the DB creation script manually, but it says it won't create any DB because they exist...

Note 2: I've read some people had similar issues with the sync engine, and they said they solved it running `setup.sh`. I tried that, and it seems to update some packages, and then ends up with:
```
Ensuring libsodium version...
Ensuring redis version...
Downloading and installing redis-2.8.17...
######################################################################## 100.0%
./setup.sh: line 172:   535 Segmentation fault      make -j2
```

**Comment by miguelrs** [comment]
I did a bit of research and looks to me like it _might_ be related to Python versions, but I have no idea about Python 😓 

Also noticed the mysql image has an update from a couple of days ago. Not sure if this can be reason...
```
 $ >> docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
mysql                      latest              0e7ce207390e        2 days ago          400.2 MB
nhurel/nylas-sync-engine   latest              83fdf9371956        4 days ago          867.4 MB
redis                      latest              d59dc9e6d0bf        4 weeks ago         182.9 MB
```

**Comment by nhurel** [comment]
With latest version of sync-engine, I encountered issue with python load path too (I'm not familiar with python, neither). I fixed the issue by adding an environment variable PYTHONPATH set to `/opt/sync-engine` but didn't think of running bin/inbox-auth with sudo.

As a workaround, you can run `sudo -uinbox PYTHONPATH=. bin/inbox-auth my-email@gmail.com`.

I'll try to find a cleaner solution to run this command, though.

**Comment by miguelrs** [comment]
yay! `sudo -uinbox PYTHONPATH=. bin/inbox-auth my-email@gmail.com` worked for me 🎉 

Thanks _a lot_ for the repo and quick and accurate support 👍 

Feel free to close this unless you want to keep it open as a reminder / for other people to give solutions...
