### ISSUE TITLE
i pull nylas-sync-engine from dockerhub,but run error

### ISSUE THREAD

**Issue by soenter** [nhurel/nylas-sync-engine#5]
Traceback (most recent call last):
  File "bin/create-db", line 10, in <module>
    from inbox.ignition import init_db, build_uri, EngineManager, verify_db
  File "/opt/sync-engine/inbox/ignition.py", line 141, in <module>
    config.get_required('DATABASE_USERS'))
  File "/opt/sync-engine/inbox/ignition.py", line 131, in **init**
    port=port)
  File "/opt/sync-engine/inbox/ignition.py", line 36, in build_uri
    password=urlquote(password),
  File "/usr/lib/python2.7/urllib.py", line 1272, in quote_plus
    if ' ' in s:
TypeError: argument of type 'NoneType' is not iterable
[INFO]  \* Restarting with stat
Traceback (most recent call last):
  File "/opt/sync-engine/bin/inbox-start", line 29, in <module>
    from inbox.mailsync.service import SyncService
  File "/opt/sync-engine/inbox/mailsync/service.py", line 12, in <module>
    from inbox.contacts.remote_sync import ContactSync
  File "/opt/sync-engine/inbox/contacts/remote_sync.py", line 8, in <module>
    from inbox.models import Contact, Account
  File "/opt/sync-engine/inbox/models/**init**.py", line 31, in <module>
    from inbox.models.backends import module_registry as backend_module_registry  # noqa
  File "/opt/sync-engine/inbox/models/backends/**init**.py", line 8, in <module>
    module_registry = register_backends(**name**, **path**)
  File "/opt/sync-engine/inbox/util/misc.py", line 181, in register_backends
    modules = load_modules(base_name, base_path)
  File "/opt/sync-engine/inbox/util/misc.py", line 167, in load_modules
    full_module_name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/opt/sync-engine/inbox/models/backends/gmail.py", line 12, in <module>
    from inbox.models.session import session_scope
  File "/opt/sync-engine/inbox/models/session.py", line 11, in <module>
    from inbox.ignition import engine_manager
  File "/opt/sync-engine/inbox/ignition.py", line 141, in <module>
    config.get_required('DATABASE_USERS'))
  File "/opt/sync-engine/inbox/ignition.py", line 131, in **init**
    port=port)
  File "/opt/sync-engine/inbox/ignition.py", line 36, in build_uri
    password=urlquote(password),
  File "/usr/lib/python2.7/urllib.py", line 1272, in quote_plus
    if ' ' in s:
TypeError: argument of type 'NoneType' is not iterable
s6-svscan: warning: unable to exec finish script .s6-svscan/finish: No such file or directory
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan: fatal: unable to exec .s6-svscan/crash: No such file or directory

**Comment by ConorIA** [comment]
Are you running with the docker-compose example provided in the repo readme? The sync-engine container requires linked mysql and redis containers.

**Comment by soenter** [comment]
i see  ,thanks!

**Comment by nhurel** [comment]
Thank you for your answer @ConorIA ;-)
